# Generated by Django 4.1 on 2022-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cover",
            field=models.ImageField(blank=True, upload_to="recipes/covers/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
